---
# Source: arangodb-operator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arango-ade-operator
  annotations:
      strategy.spinnaker.io/recreate: "true"
  namespace: hmqaaws
  labels:
      app.kubernetes.io/name: arangodb-operator
      #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/instance: ade
      release: ade
imagePullSecrets:
  - name: bmc-dtrhub
---
# Source: arangodb-operator/templates/deployment-operator/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: arango-ade-operator-hmqaaws-rbac-deployment
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["namespaces", "nodes", "persistentvolumes"]
      verbs: ["get", "list"]
---
# Source: arangodb-operator/templates/deployment-replications-operator/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: arango-ade-operator-hmqaaws-rbac-deployment-replication
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["namespaces", "nodes"]
      verbs: ["get", "list"]
---
# Source: arangodb-operator/templates/deployment-operator/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: arango-ade-operator-hmqaaws-rbac-deployment
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: arango-ade-operator-hmqaaws-rbac-deployment
subjects:
    - kind: ServiceAccount
      name: arango-ade-operator
      namespace: hmqaaws
---
# Source: arangodb-operator/templates/deployment-replications-operator/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: arango-ade-operator-hmqaaws-rbac-deployment-replication
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: arango-ade-operator-hmqaaws-rbac-deployment-replication
subjects:
    - kind: ServiceAccount
      name: arango-ade-operator
      namespace: hmqaaws
---
# Source: arangodb-operator/templates/deployment-operator/default-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: arango-ade-operator-rbac-default
    namespace: hmqaaws
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get"]
---
# Source: arangodb-operator/templates/deployment-operator/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: arango-ade-operator-rbac-deployment
    namespace: hmqaaws
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
rules:
    - apiGroups: ["database.arangodb.com"]
      resources: ["arangodeployments", "arangodeployments/status","arangomembers", "arangomembers/status"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "secrets", "serviceaccounts"]
      verbs: ["*"]
    - apiGroups: ["apps"]
      resources: ["deployments", "replicasets"]
      verbs: ["get"]
    - apiGroups: ["policy"]
      resources: ["poddisruptionbudgets"]
      verbs: ["*"]
    - apiGroups: ["backup.arangodb.com"]
      resources: ["arangobackuppolicies", "arangobackups"]
      verbs: ["get", "list", "watch"]
---
# Source: arangodb-operator/templates/deployment-replications-operator/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: arango-ade-operator-rbac-deployment-replication
    namespace: hmqaaws
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
rules:
    - apiGroups: ["replication.database.arangodb.com"]
      resources: ["arangodeploymentreplications", "arangodeploymentreplications/status"]
      verbs: ["*"]
    - apiGroups: ["database.arangodb.com"]
      resources: ["arangodeployments"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "secrets"]
      verbs: ["*"]
    - apiGroups: ["apps"]
      resources: ["deployments", "replicasets"]
      verbs: ["get"]
---
# Source: arangodb-operator/templates/deployment-operator/default-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: arango-ade-operator-rbac-default
    namespace: hmqaaws
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: arango-ade-operator-rbac-default
subjects:
    - kind: ServiceAccount
      name: default
      namespace: hmqaaws
---
# Source: arangodb-operator/templates/deployment-operator/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: arango-ade-operator-rbac-deployment
    namespace: hmqaaws
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: arango-ade-operator-rbac-deployment
subjects:
    - kind: ServiceAccount
      name: arango-ade-operator
      namespace: hmqaaws
---
# Source: arangodb-operator/templates/deployment-replications-operator/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: arango-ade-operator-rbac-deployment-replication
    namespace: hmqaaws
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: arango-ade-operator-rbac-deployment-replication
subjects:
    - kind: ServiceAccount
      name: arango-ade-operator
      namespace: hmqaaws
---
# Source: arangodb-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: arango-ade-operator
  namespace: hmqaaws
  annotations:
        strategy.spinnaker.io/recreate: "true"
  labels:
    app.kubernetes.io/name: arangodb-operator
    #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
    # app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ade
    release: ade
spec:
  ports:
    - name: server
      port: 8528
      protocol: TCP
      targetPort: 8528
  selector:
    app.kubernetes.io/name: arangodb-operator
    # app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ade
    release: ade
    role: leader
  type: ClusterIP
---
# Source: arangodb-operator/templates/deployment.yaml
# Scope "legacy" selected
apiVersion: apps/v1
kind: Deployment
metadata:
    name: arango-ade-operator
    namespace: hmqaaws
    annotations:
        strategy.spinnaker.io/recreate: "true"
    labels:
        app.kubernetes.io/name: arangodb-operator
        #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
        # app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ade
        release: ade
spec:
    replicas: 2
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app.kubernetes.io/name: arangodb-operator
            # app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/instance: ade
            release: ade
    template:
        metadata:
            labels:
                app.kubernetes.io/name: arangodb-operator
                #helm.sh/chart: arangodb-operator-22.2.01-RC2SHA7cb437e2BUILD2
                # app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/instance: ade
                release: ade
            annotations:
                strategy.spinnaker.io/recreate: "true"
        spec:
            serviceAccountName: arango-ade-operator
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: beta.kubernetes.io/arch
                          operator: In
                          values:
                          - "amd64"
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      topologyKey: "kubernetes.io/hostname"
                      labelSelector:
                        matchExpressions:
                          - key: app.kubernetes.io/name
                            operator: In
                            values:
                              - arangodb-operator
                          - key: app.kubernetes.io/instance
                            operator: In
                            values:
                              - ade
            hostNetwork: false
            hostPID: false
            hostIPC: false
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
            imagePullSecrets:
            - name: bmc-dtrhub
            containers:
                - name: operator
                  imagePullPolicy: IfNotPresent
                  image: "containers.bmc.com/bmc/lpade:kube-arangodb-22.2.01-RC2SHA7cb437e2BUILD2"
                  args:
                    - --scope=legacy
                    - --operator.deployment
                    - --operator.deployment-replication



                    - --chaos.allowed=false
                  env:
                      - name: MY_POD_NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                      - name: MY_POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: MY_POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: RELATED_IMAGE_UBI
                        value: "alpine:3.11"
                      - name: RELATED_IMAGE_METRICSEXPORTER
                        value: "map[imagename:arangodb-exporter org:bmc/lpade registryhost:bmc-dtrhub tag:0.1.7 tagprefix:-]"
                      - name: RELATED_IMAGE_DATABASE
                        value: "map[imagename:arangodb org:bmc/lpade registryhost:containers.bmc.com tag:22.2.01-RC2SHA7cb437e2BUILD2 tagprefix:-]"
                  ports:
                      - name: metrics
                        containerPort: 8528
                  securityContext:
                      privileged: false
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      capabilities:
                          drop:
                              - 'ALL'
                  resources:
                      limits:
                        cpu: 1
                        memory: 768Mi
                      requests:
                        cpu: 250m
                        memory: 256Mi
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 8528
                          scheme: HTTPS
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 8528
                          scheme: HTTPS
                      initialDelaySeconds: 5
                      periodSeconds: 10
            tolerations:
                - key: "node.kubernetes.io/unreachable"
                  operator: "Exists"
                  effect: "NoExecute"
                  tolerationSeconds: 5
                - key: "node.kubernetes.io/not-ready"
                  operator: "Exists"
                  effect: "NoExecute"
                  tolerationSeconds: 5
